webtalk_init -webtalk_dir C:/Users/vitor/Documents/UERGS/2021.1/Organização de Computadores/Trabalho/mips-main/miTo.sim/sim_1/behav/xsim/xsim.dir/testebench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 24 18:12:53 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "201af498-ca6f-40c3-814e-5295a83837cd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6b16120a2d824e05bcce677717a8d6fd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "346" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6476_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1537703134 -regid "" -xml C:/Users/vitor/Documents/UERGS/2021.1/Organização de Computadores/Trabalho/mips-main/miTo.sim/sim_1/behav/xsim/xsim.dir/testebench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/vitor/Documents/UERGS/2021.1/Organização de Computadores/Trabalho/mips-main/miTo.sim/sim_1/behav/xsim/xsim.dir/testebench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/vitor/Documents/UERGS/2021.1/Organização de Computadores/Trabalho/mips-main/miTo.sim/sim_1/behav/xsim/xsim.dir/testebench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
